global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'websocket-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:9091']
        labels:
          instance: 'websocket-server-1'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
